repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==22.3.0]
        args: [--nbqa-mutate]
      - id: nbqa-flake8
        additional_dependencies: [flake8==3.9.2]
  - repo: local
    hooks:
      - id: check-headers
        name: check-headers
        description: Check that headers start with H2.
        language: python
        entry: python scripts/check_headers.py
        additional_dependencies: ["nbformat", "rich"]
        files: "ipynb"
